### ISSUE TITLE
Is Data8 DataverseClient thread safe?

### ISSUE THREAD

**Issue by me13742** [Data8/DataverseClient#42]
Hello, I wonder is Data8 DataverseClient works in a multi-threaded environment?

**Comment by MarkMpn** [comment]
You should use the `.Clone()` method to create a new instance for use in separate threads. You can use the same pattern as described for the ServiceClient class at https://colinvermander.wordpress.com/2020/03/26/cdsserviceclient-with-asp-net-core/

**Comment by me13742** [comment]
Thanks for your response
 I encountered another issue
 I created a new instance of the service client for each request, but when I had too many requests at the same time (e.g., 100 requests per second), my application crashed with the error message: 'dial tcp ...:443: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.'
_var client = new OnPremiseClient(setting.OrganizationServiceAddress, setting.UserName, setting.Password);
            client.EnableProxyTypes();_
            so  I made the service static, but I'm concerned that this approach might make my application slow because all requests are now using the same service instance.
            _var serviceFactory = new CrmServiceProxyFactory(CrmSettingManager);
            service ??= serviceFactory.CreateInstance();_
            I'm wondering if there's a solution to this problem, or if using the .Clone() method could help.

**Comment by MarkMpn** [comment]
The `.Clone()` method should help as it can bypass some of the requests needed to get the service details, but you're still likely to get port exhaustion at that rate. You could consider using pooling to limit the number of instances created and reuse them rather than creating new instances each time - see https://learn.microsoft.com/en-us/aspnet/core/performance/objectpool?view=aspnetcore-8.0
