### ISSUE TITLE
Support for HTTP only

### ISSUE THREAD

**Issue by vmcbaptista** [Data8/DataverseClient#8]
Is there any plan to support instances with only HTTP binding?

I have no idea of what actually needs to be done to properly support it, but if you guide me, I might be able to help.

**Comment by yassinsayed** [comment]
HI thanks for the great effort but i am getting the below error, where i can access the organization using SSL 
https://cedemo.xxx.xxx/XRMServices/2011/Organization.svc

The provided URI scheme 'http' is invalid; expected 'https'. (Parameter 'via')

is there any missing or change required

**Comment by MarkMpn** [comment]
Can you please check that the SSL binding is created on the IIS server, and in [Deployment Manager](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/deploy/configure-claims-based-authentication?view=op-9-0#configure-claims-based-authentication-1) the binding type is set to HTTPS?

If that all looks OK, can you send me a Fiddler log of the requests and the full call stack of the exception please?

**Comment by yassinsayed** [comment]
I sent you an email containing the fiddler log; I am looking for your advice

**Comment by MarkMpn** [comment]
It looks like you've sent the log file for Fiddler rather than the trace of the requests it's captured. Can you please run the test again but then click the Save button in Fiddler - this should save a .saz file that contains all the HTTP request and responses.

**Comment by yassinsayed** [comment]
done file sent waiting your feedback please

**Comment by yassinsayed** [comment]
![image](https://user-images.githubusercontent.com/34830420/175968125-704b07dc-ea90-49ea-a288-54c59bbd20ae.png)
  please see the image

**Comment by MarkMpn** [comment]
Sorry, I can't see your file anywhere. Can you send it again to onprem@markcarrington.dev please?

**Comment by MarkMpn** [comment]
Thanks for the updated file @yassinsayed. It looks like your ADFS server is advertising a `/adfs/services/trust/13/username` endpoint using HTTP rather than HTTPS. The other endpoints all use HTTPS as expected.

One possible solution may be to simply [disable this endpoint as described in this article](https://docs.microsoft.com/en-GB/previous-versions/troubleshoot/dynamics/crm/dynamics-crm-outlook-fails-to-set-to-external-ifd-web-address) so it should then use the `/adfs/services/trust/13/usernamemixed` endpoint instead.

**Comment by MengSung** [comment]
After disable the endpoint
I got this error message

System.ServiceModel.ActionNotSupportedException: 'The message with Action ‘http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Create ' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver. Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).'

Could you help me to solve this problem,thanks.

**Comment by MarkMpn** [comment]
@MengSung Please check you have set up the bindings in Deployment Manager correctly  - see https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/deploy/post-installation-configuration-guidelines-dynamics-365?view=op-9-1&WT.mc_id=DX-MVP-5004203#configuring-dynamics-365-for-https

**Comment by madxfr** [comment]
Hello,
I'm on premise and i have the same error that @yassinsayed.
`The provided URI scheme 'http' is invalid; expected 'https'. (Parameter 'via')`
Everything is configurated with HTTPS.

I did a capture with Fiddler but i don't know how to see the endpoint advertised by the ADFS.
Could you help me.

Thanks

**Comment by yassinsayed** [comment]
Hi thanks Data8, browse Adfs and search then disable  the below record

One possible solution may be to simply disable this endpoint as described in this article<https://docs.microsoft.com/en-GB/previous-versions/troubleshoot/dynamics/crm/dynamics-crm-outlook-fails-to-set-to-external-ifd-web-address> so it should then use the /adfs/services/trust/13/usernamemixed endpoint instead

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by madxfr** [comment]
I disabled the endpoint but I have this error on VS

> The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.

**Comment by MarkMpn** [comment]
@madxfr You might be able to get some more information about what's going wrong in the Application event log on the CRM web server. Feel free to send me your Fiddler logs at onprem@markcarrington.dev alongside those error details.

**Comment by madxfr** [comment]
Problem solve.
The login need to be in that format : username@domain.com and not domain.com\\username or domain.com\username

Thanks for your great job

**Comment by yassinsayed** [comment]
Dear,

i sent your the .saz file and thanks in forward.

________________________________

**Comment by yassinsayed** [comment]
Problem solved thx

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johnkaku** [comment]
Disabling completely username, worked.
However disabling only on proxy and kipping enabled does not work, why?

Is there any way to configure the dataverse client to log verbosely the responses and requests to/from ADFS for debugging?
